# Homework 2
樊青远 12232509

In this homework, we create a vanilla feed-forward neural network with 2 inputs, 3 outputs, and 1 hidden layer with 2 nodes and bias on the hidden layer and output layer and calculate its forward feed result, categorical cross entropy loss, and gradient of the loss with respect to the weights.

First , we import the necessary libraries.

In [1]:
# import libraries
import torch
from torch import nn

Second, we define the input data with a given torch random seed, the target data, the weights, and the bias.

In [2]:
# Make data
torch.manual_seed(4321)
X = torch.rand(size=(8, 2))
y = torch.randint(low=0, high=3, size=(8,))


In [3]:
# print input data
print(X)
print(y)

tensor([[0.1255, 0.5377],
        [0.6564, 0.0365],
        [0.5837, 0.7018],
        [0.3068, 0.9500],
        [0.4321, 0.2946],
        [0.6015, 0.1762],
        [0.9945, 0.3177],
        [0.9886, 0.3911]])
tensor([0, 2, 2, 0, 2, 2, 0, 1])


After that, we define the network by using `nn.Module`:

In [4]:
# construct a vanilla feed-forward neural network with 2 inputs, 3 outputs, and 1 hidden layer with 2 nodes and bias on the hidden layer and output layer
class Vanilla(nn.Module):
    def __init__(self):
        super(Vanilla, self).__init__()
        # define the linear connection layer
        self.fc1 = nn.Linear(2, 2, bias=True)
        self.fc2 = nn.Linear(2, 3, bias=True)
        self.logistic_activate_func = nn.Sigmoid()
        self.softmax = nn.Softmax(dim=1)
    
    # specify the initial weight
    def init_weight(self):
        self.fc1.weight.data = torch.tensor([[0.48, -0.51], [-0.43, -0.48]], dtype=torch.float)
        self.fc1.bias.data = torch.tensor([0.23, 0.05], dtype=torch.float)
        self.fc2.weight.data = torch.tensor([[-0.99, -0.66], [0.36, 0.34], [-0.75, 0.66]], dtype=torch.float)
        self.fc2.bias.data = torch.tensor([0.32, -0.44, 0.70], dtype=torch.float)

    # connect the components of the network
    def forward(self, x):
        x = self.fc1(x)
        x = self.logistic_activate_func(x)
        x = self.fc2(x)
        x = self.softmax(x)
        return x

Lastly, we calculate the forward feed result, categorical cross entropy loss, and gradient of the loss with respect to the weights.

In [6]:
# use and prediction the model
model = Vanilla()
model.init_weight()
print("predictions of the network:")
print(model(X))


# loss
loss = nn.CrossEntropyLoss()
print("categorical cross entropy loss:")
print(loss(model(X), y))

# calculate the gradient
model.zero_grad()
loss(model(X), y).backward()

# print the gradient
print("gradient of the weights of fc1:")
print(model.fc1.weight.grad)
print("gradient of the bias of fc1:")
print(model.fc1.bias.grad)
print("gradient of the weights of fc2:")
print(model.fc2.weight.grad)
print("gradient of the bias of fc2:")
print(model.fc2.bias.grad)


predictions of the network:
tensor([[0.1867, 0.2663, 0.5470],
        [0.1747, 0.2958, 0.5295],
        [0.1959, 0.2738, 0.5303],
        [0.2022, 0.2590, 0.5388],
        [0.1812, 0.2820, 0.5368],
        [0.1787, 0.2902, 0.5311],
        [0.1863, 0.2966, 0.5171],
        [0.1886, 0.2943, 0.5171]], grad_fn=<SoftmaxBackward0>)
categorical cross entropy loss:
tensor(1.0681, grad_fn=<NllLossBackward0>)
gradient of the weights of fc1:
tensor([[ 0.0057,  0.0067],
        [-0.0017,  0.0058]])
gradient of the bias of fc1:
tensor([0.0167, 0.0001])
gradient of the weights of fc2:
tensor([[-0.0059, -0.0053],
        [ 0.0323,  0.0252],
        [-0.0264, -0.0199]])
gradient of the bias of fc2:
tensor([-0.0157,  0.0579, -0.0422])
